# Source: acme/templates/cert-manager-prod-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    meta.helm.sh/release-name: 'acme-jx'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "thebassaw@gmail.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    preferredChain: "ISRG Root X1"
    solvers:
    - selector:
        dnsNames:
        - "*.jenkinx.auroraverusschool.org"
        - "jenkinx.auroraverusschool.org"
      # ACME DNS-01 provider configurations
      dns01:
        route53:
          region: us-east-2
