# Source: external-dns/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-jx
  labels:
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-6.20.3
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'cluster'
  annotations:
    meta.helm.sh/release-name: 'external-dns'
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - nodes
  - endpoints
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - "networking.k8s.io"
  - getambassador.io
  resources:
  - ingresses
  - hosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zalando.org
  resources:
  - routegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zalando.org
  resources:
  - routegroups/status
  verbs:
  - patch
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - gloo.solo.io
  - gateway.solo.io
  resources:
  - proxies
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - tcpingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  - tlsroutes
  - tcproutes
  - udproutes
  - grpcroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cis.f5.com
  resources:
  - virtualservers
  verbs:
  - get
  - watch
  - list
