# Source: kuberhealthy/templates/khcheck-dns-internal.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-internal-service-role
  namespace: kuberhealthy
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
