apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  acme:
    server: {{ .Values.clusterissuer.acme.server }}
    email: {{ .Values.clusterissuer.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.acme.privateKeySecretRef.name }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.clusterissuer.acme.solvers.http01.ingress.class }}
    - dns01:
        route53:
          accessKeyIDSecretRef:
            key: ACCESS_KEY
            name: env-route53
          region: us-east-2
          secretAccessKeySecretRef:
            key: SECRET_KEY
            name: env-route53
      selector:
        dnsZones:
        - 'api8.devops.auroraverusschool.org'
        - '*.api8.devops.auroraverusschool.org'
