apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.postgresql.namespace }}
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: {{ .Values.postgresql.name }}