apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.ports }}
  type: {{ .Values.service.type }}
